title: Krishna Belel
logo: /assets/img/profile.jpg
description: Software QA Engineer
theme: jekyll-theme-minimal
include:
  - assets/
navigation:
  - title: Home
    url: /
  - title: LeetCode Problems
    url: /leetcode/